### ISSUE TITLE
"Unhandled exception. Could not find file '...\gameInfo.db'

### ISSUE THREAD

**Issue by takano32** [RupertAvery/PSXPackager#46]
### Discussed in https://github.com/RupertAvery/PSXPackager/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **RealPhali** May 20, 2023</sup>
Hi there. I keep getting the same error every time I try to run this:

```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'c:\Roms\PS1\Resources\gameInfo.db'.
File name: 'c:\Roms\PS1\Resources\gameInfo.db'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Popstation.Database.GameDB..ctor(String path)
   at PSXPackager.Program.ProcessFiles(ProcessOptions options)
   at PSXPackager.Program.<>c__DisplayClass2_0.<Main>b__0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PSXPackager.Program.Main(String[] args)
```

I've reinstalled NET Runtime, both 6 and 7, and I have no idea where I'm doing something wrong.</div>

**Comment by fhcat** [comment]
I am getting the same error. How did you resolve it?

**Comment by matiaslauriti** [comment]
> I am getting the same error. How did you resolve it?

I just got the same error, download it from the [previous version](https://github.com/RupertAvery/PSXPackager/releases/tag/v1.6.0). The [current release](https://github.com/RupertAvery/PSXPackager/releases/tag/v1.6.1) has files missing, even the GUI was not working, but using the previous version, the GUI worked again and the CLI too

**Comment by RupertAvery** [comment]
There seems to be an issue with dotnet publish for the windows builds. The database file isn't included in the output. I'll include the file in the build manually for now.
