### ISSUE TITLE
Merging a two-disk game to one pbp

### ISSUE THREAD

**Issue by finnlogin** [RupertAvery/PSXPackager#50]
Hi there!

I tried to convert Abe's Exoddus to PBP format using your utility, but unfortunately without success so far.
The game consists of two disks (cue + bin). Thus, four files in total need to be merged.
Following your instructions, I created an m3u file with the following lines, which I saved in the files directory:
```
Oddworld - Abe's Exoddus (USA) (Disc 1).bin
Oddworld - Abe's Exoddus (USA) (Disc 1).cue
Oddworld - Abe's Exoddus (USA) (Disc 2).bin
Oddworld - Abe's Exoddus (USA) (Disc 2).cue
```

The PBP file was created, but it doesn't work on my PS Vita. Apparently, I did something wrong.
Could you please help me figure out how to create a valid PBP file ? I would appreciate any help in this matter.

Viacheslav

**Comment by RupertAvery** [comment]
Sorry for the delay!

You should just put the .cue file.  The .cue file references one or more .bin files per disc (a .bin can either be data or audio - the .cue is a text file that says what sector the .bin is located in a)

**Comment by MeatballSub** [comment]
$ psxpackager.exe -i "Driver 2.m3u"
PSXPackager v1.6.2 by RupertAvery

Input : Driver 2.m3u
Output:
Compression Level: 5

Processing started: 12:29:14
Processing Driver 2.m3u
Found 2 entries
Found SLUS01161 "Driver 2 - Disc 1"
Found SLUS01318 "Driver 2 - Disc 2"
Using Title 'Driver 2'
Writing Disc 1 - Unhandled exception. System.IO.IOException: The handle is invalid.
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at System.Console.set_CursorVisible(Boolean value)
   at PSXPackager.ConsoleNotifier.Notify(PopstationEventEnum event, Object value)
   at PSXPackager.AggregateNotifier.Notify(PopstationEventEnum event, Object value)
   at Popstation.Processing.ProcessFile(String file, ProcessOptions options, CancellationToken cancellationToken)
   at PSXPackager.Program.ProcessFiles(ProcessOptions options)
   at PSXPackager.Program.<>c__DisplayClass2_0.<Main>b__0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PSXPackager.Program.Main(String[] args)

$ cat Driver\ 2.m3u
Driver 2 (USA) (Disc 1).cue
Driver 2 (USA) (Disc 2).cue

$ cat "Driver 2 (USA) (Disc 1).cue"
FILE "Driver 2 (USA) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

$ cat "Driver 2 (USA) (Disc 2).cue"
FILE "Driver 2 (USA) (Disc 2).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by RupertAvery** [comment]
> System.IO.IOException: The handle is invalid.
> at System.ConsolePal.set_CursorVisible(Boolean value)

This doesn't seem to be an issue with the processing code. It looks as if its with the Console displaying the progress. What OS / shell are you running it on?

**Comment by MeatballSub** [comment]
> > System.IO.IOException: The handle is invalid.
> > at System.ConsolePal.set_CursorVisible(Boolean value)
> 
> This doesn't seem to be an issue with the processing code. It looks as if its with the Console displaying the progress. What OS / shell are you running it on?

Windows 11
MSYS2 terminal that comes with git for windows
Windows PowerShell works
Command Prompt also works

Consider me surprised that choice of terminal affects this.

I'm usually more comfortable with command line utilities, and I had intended to wrap the call in a loop in a bash script.  However, when I experienced the issue, I took a look at the gui, and found you'd already created a batch mode that served my purposes nicely(even looks like it might be parallelized, nice touch!)

**Comment by RupertAvery** [comment]
Great to hear.  In case I'd ever want to fix this, it seems to be related to `IsOutputRedirected`.

https://github.com/dotnet/runtime/issues/28625#issuecomment-460736213

I actually thought of parallelization in the CLI, it's just that displaying parallel updates would have been challenging.
